### ISSUE TITLE
Using keybox in a git repo?

### ISSUE THREAD

**Issue by johnlauck** [copiousfreetime/keybox#1]
Is there a setup that would allow keybox to be used to share passwords among a team?  We would like to have a git repo that stores the passwords, but with the current binary data and record digest I don't see it working across multiple users' commits.

**Comment by copiousfreetime** [comment]
I think it would be fine, the procedure you would have to follow is there is no merging on that the keybox.yml file.  If you were to use it you would need to make sure that you always had the most recent version before adding a new entry.  It is a yaml file, so its really all text, just uuencoded or however yaml serializes a binary blob to disk.
