### ISSUE TITLE
Adding records does not work with Psych YAML

### ISSUE THREAD

**Issue by ytti** [copiousfreetime/keybox#6]
I tried this in record.rb
      #def to_yaml(*args)
      #  Keybox.fix_encoding( *@data_members.values )
      #  super
      #end

```
  # FIXME use of this method is deprecated in ruby 1.9
  #def to_yaml_properties
  #  properties = %w{ @creation_time @modification_time
  #                   @last_access_time @data_members @uuid }
  #  # FIXME is there a better way?
  #  if RUBY_VERSION =~ /1.9/ or RUBY_VERSION =~ /2.0/
  #    properties = properties.map { |p| p.to_sym }
  #  end
  #  properties
  #end

  def encode_with coder
    Keybox.fix_encoding( *@data_members.values )
    properties = %w{ @creation_time @modification_time
                     @last_access_time @data_members @uuid }
    properties.each do |property|
      coder[property[1..-1]] = instance_variable_get property
    end
  end
```

and this in uuid.rb:
    ##def to_yaml(*args)
    ##  Keybox.fix_encoding @bytes if @bytes
    ##  super
    ##end

```
def encode_with coder
  Keybox.fix_encoding @bytes if @bytes
  coder['bytes'] = @bytes
end
```

It sort of works, 'keybox -a moi' and adding just hostname 'moi', it adds it, and I can fetch it correctly.
But if I try 'keybox -e moi' and change title to 'moi2' (leave hostname unchanged), title becomes mangled:
1. bW9pMg==
       hostname : moi

It is deterministically wrong though, so shouldn't be too hard to figure out what is going wrong.

**Comment by copiousfreetime** [comment]
Thanks for the bug report, keybox needs lots of work at the moment, I'm not sure if I'll get to this right now, feel free to submit a pull request.

**Comment by copiousfreetime** [comment]
right now all the tests are passing in ruby 2.0. Please give it a go and see if it works for you. I do have a problem where files written with 1.8.7 are not being read by 1.9.3 or 2.0 so I'm working on that right now.

**Comment by copiousfreetime** [comment]
I've opened issue #7 to handle what I talked about.

I still see this issue with ruby 2.0.

**Comment by copiousfreetime** [comment]
@ytti  have pushed a new update which I think cleans everything up. If you could pull down this latest code and run https://github.com/copiousfreetime/keybox/blob/master/bin/keybox-db-upgrade on your test database (using ruby 1.9.3) and then you should be able to use 1.8.7, 1.9.3 and 2.0 all against that new database and it should work.

Run it all through your gauntlet and let me know what you think. If it works for you I'll push the gem.

**Comment by ytti** [comment]
Looks pretty good! I had to do this for conversion to work:

record.rb, line 59
new_data_members[k] = String.new(v).encode( 'UTF-8', {:invalid=>:replace, :undef=>:replace, :replace=>'?'} )

And it would replace unrecognized characters with '?' basically I had UTF8 in db, but it was interpreted as ascii-8bit.
Further, if I try to add new data with UTF8 encoding, it won't work.

[1 ytti@lintukoto ~]% keybox -a test
Password for (/home/ytti/.keybox/database.yaml) : *
Gathering information for entry 'test'
       title [test] : test
    hostname [test] : ä
        username [] : ä
           password : **
   password (again) : **

##  additional_info [] : ä

```
       title : test
    hostname : ä
    username : ä
    password :  ***** private ***** 
```

 additional_info : ä

---

Is this information correct? (y/n) y
Adding test to database.
Database modified, saving.
Error: incompatible character encodings: ASCII-8BIT and UTF-8

Curiously when I press 'ä' in password, I get two stars, quite clear indication that it's not handled as UTF8 char, but as 2*8bit char.
This may be feature, unsure.

**Comment by copiousfreetime** [comment]
@ytti Thanks, I've created two new issues to deal with those. For #8 can you drop a gist of a sample db that exhibits the character conversion issue?
